# https://docs.travis-ci.com/user/languages/php/
# https://docs.travis-ci.com/user/reference/trusty/
language: php

php:
  - "7.1"
  - "7.1.24"

before_install:
  - curl -sSfL -o /usr/local/bin/phpcs https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar && chmod +x /usr/local/bin/phpcs
  - curl -sSfL -o /usr/local/bin/phpcbf https://squizlabs.github.io/PHP_CodeSniffer/phpcbf.phar && chmod +x /usr/local/bin/phpcbf

install:
  - composer install

script:
  - phpcs
  - phpunit