# https://docs.travis-ci.com/user/languages/php/
# https://docs.travis-ci.com/user/reference/trusty/
# http://www.ruanyifeng.com/blog/2017/12/travis_ci_tutorial.html
language: php
sudo: required

php:
  - "7.1"
  - "7.1.24"

before_install:
  - sudo wget -O /usr/local/bin/phpcs https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar && sudo chmod +x /usr/local/bin/phpcs
  - sudo wget -O /usr/local/bin/phpcbf https://squizlabs.github.io/PHP_CodeSniffer/phpcbf.phar && sudo chmod +x /usr/local/bin/phpcbf

install:
  - composer install

script:
  - phpcs
  - phpunit
  - php tests/coverage-check.php